

* Object hierarchy

** Group of objects held by root view
   These aren't held by other aorobjects.

** Children of root objects
   The distinction here is that root objects, and consequently their
   children, must linger. 

   For all children that have completed their animations, we should
   keep those around and just start the animation for children
   objects.

   This entails remembering a recursive drawing session. 

** Root view

   Changes to the root layer, this is where the fade out to an
   aorobject layer should be performend. 

* Performance
** Keep high depth objects around
   Delete the objects from memory after we use them, but only if their
   depth is lower than a set threshold. This way, we only keep around
   objects that are very frequently redrawn, especially the first
   level. Those at the deeper levels are not always reached.

   We do this by checking depth, then deleting child objects on lower
   levels. 

*** Remove their layers from the self objects layer. 

*** Watch out for 
    Having the objects around a priori might make them draw faster.

** TODO Ensure only children number of objects exist at each level
   If there is a way to programmatically test for this that would be ideal.

* Visual Upgrades
** TODO Color the objects
** TODO Color each level
** TODO Pick random colors or from a given set "theme"
   Just a way to have the colors changing, and the themes would be
   recursive colors that go nicely.
** Find a way to change the stroke style
   There might be a library of stroke styles. 
** Some awesome visual effect library
** Maintain and transform path
   When a path begins animating, it maintains a percentage "of the
   way" it finished animating. 

   Normally, we can stretch a path while it's still drawn. So, we
   should be able to combine this stretch and draw the path the
   percentage of the way it has finished animating. 

   The ultimate goal here is to keep the animation flowing endlessly
   and have the shapes morph into each other or fade out and new ones
   begin. 

** TODO Fade out dead animations while drawing new ones 
   This one should actually be easy. When redrawing the canvas, simply
   set the animation of the existing object to fade out, this should
   take effect immediately. 

   We always have one of each object. But in order to have an object
   fade out, and be able to create a new one, we need to copy over the
   layer and its paths that have already been drawn ?? 

*** If the paths are already drawn
    We just take the layers and the paths stay with the aorobject

*** If not
    Then theoretically we need to copy the whole object. Should still
    be doable, but getting only the layer would be much better. 


   
